---
version: "3.7"
services:
  vigilance_cockpit_mobile_frontend:
    image: "ghcr.io/sedimentum/vigilance_cockpit_mobile_frontend:${TAG:?Must specify TAG}"
    restart: always
    volumes:
      - ./.env:/app/.env.local # mount .env file for react-env into container
    environment:
      - NODE_ENV=production
    ports:
      - 3002:3000
